name: "harbouros"
version: "1.0.0"
profile: "harbouros"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  harbouros:
    +materialized: table
